from util import *
import os
# 'tax_level', 'reads_taxon_path', 'ref_taxon_path', 'mapping_reads_ref_path', 'reads_sep', 'contigs_sep', 'mpp_sep', 'output_sep', 'output_path', 'file_to_use'
extensions = ['tax', 'tax', 'txt']
type_files = ['reads', 'contigs', 'mapping']
# 5
# 4
if len(sys.argv) == 6:
    titles = ('file_path', 'reads_sep', 'contigs_sep', 'mpp_sep', 'output_sep')
elif len(sys.argv) == 5:
    titles = ('file_path', 'contigs_sep', 'mpp_sep', 'output_sep')
else:
    sys.exit('''
    You used too much or too less arguments
    python .\execTaxam.py <folder_files> <reads_sep> <contigs_sep> <mpp_sep> <output_sep>
    python .\execTaxam.py <folder_files> <contigs_sep> <mpp_sep> <output_sep>

    folder_files = Folder where are the file to be used
    reads_ses =  Separator used to part each collumn in read file
    contigs_sep =  Separator used to part each collumn in contigs file
    mpp_sep =  Separator used to part each collumn in mapping file
    out_sep =  Separator used to part each collumn in output file generated by TaxAM
    ''')

terminal = {}
for key, arg in enumerate(sys.argv[1:]):
    print(arg)
    terminal[titles[key]] = arg

# SEEING IF THIS DIRECTORY EXISTS
if(os.path.isdir(f'{terminal["file_path"]}/')):
    files = os.listdir(terminal['file_path'])
else:
    sys.exit('This directory doesnt exists')
print()

file_names = {}
type, key = 'None', 'None'
wrong_files = ''
for file in files:
    # print(file)
    print( len(file.split('_')), file, type)
    if len(file.split('_')) == 2:    
        type = getPrefix(file, '_')
        key = getSuffix(file, '_')
        if type in type_files:
            try:
                file_names[key][type] = file
            except:
                file_names[key] = {type : file}
        else:
            wrong_files += file + '\n'
    else:
        wrong_files += file + '\n'
    type, key = 'None', 'None'


if wrong_files != '':
    print('Bad files:\n' + wrong_files)
    sys.exit('''
    You used wrong files. Your files should be:

    reads_<read_id>.tax
    contigs_<contigs_id>.tax
    mapping_<mapping_id>.mp
    ''')

printDict(file_names)

